new start of the thread
sleeping for 1 sec now
sleeping for 1 sec now
new start of the thread
sleeping for 1 sec now
sleeping for 1 sec now
sleeping for 1 sec now
sleeping for 1 sec now
sleeping for 1 sec now
sleeping for 1 sec now
sleeping for 1 sec now
sleeping for 1 sec now
Exception in Tkinter callback
Traceback (most recent call last):
  File "D:\Coding\Python\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "d:/Coding/Time Clock/TimeClockV1.03.py", line 361, in clockIn
    waitThread.run()
  File "D:\Coding\Python\lib\threading.py", line 869, in run
    del self._target, self._args, self._kwargs
AttributeError: _target